"""empty message

Revision ID: 255b72f9cf8b
Revises: 2069c3b45ef4
Create Date: 2014-08-08 00:58:01.169000

"""

# revision identifiers, used by Alembic.
revision = '255b72f9cf8b'
down_revision = '2069c3b45ef4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('like', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'like')
    ### end Alembic commands ###
