"""empty message

Revision ID: 30457bf8f148
Revises: 255b72f9cf8b
Create Date: 2014-08-08 02:04:44.919000

"""

# revision identifiers, used by Alembic.
revision = '30457bf8f148'
down_revision = '255b72f9cf8b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('like', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'like')
    ### end Alembic commands ###
