"""empty message

Revision ID: 461e9542a252
Revises: 6a372a80d2a
Create Date: 2014-09-14 23:27:41.484000

"""

# revision identifiers, used by Alembic.
revision = '461e9542a252'
down_revision = '6a372a80d2a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
