"""empty message

Revision ID: 519c59820842
Revises: None
Create Date: 2014-09-13 20:43:02.791000

"""

# revision identifiers, used by Alembic.
revision = '519c59820842'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
