"""empty message

Revision ID: 6fb75e9a2ef
Revises: 1bc3a37f02cc
Create Date: 2014-08-29 03:19:07.705000

"""

# revision identifiers, used by Alembic.
revision = '6fb75e9a2ef'
down_revision = '1bc3a37f02cc'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('university',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university', sa.String(length=255), nullable=True),
    sa.Column('upper_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('location_second')
    op.add_column('location_first', sa.Column('upper_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location_first', 'upper_id')
    op.create_table('location_second',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('location_second', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('university')
    ### end Alembic commands ###
