"""empty message

Revision ID: d7eddf304e5
Revises: 6fb75e9a2ef
Create Date: 2014-08-30 17:27:14.392000

"""

# revision identifiers, used by Alembic.
revision = 'd7eddf304e5'
down_revision = '6fb75e9a2ef'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'location_second')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('location_second', mysql.VARCHAR(length=255), nullable=True))
    ### end Alembic commands ###
