"""empty message

Revision ID: 430849faa996
Revises: 4c16f83552e5
Create Date: 2014-08-05 23:15:51.107000

"""

# revision identifiers, used by Alembic.
revision = '430849faa996'
down_revision = '4c16f83552e5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
