"""empty message

Revision ID: 37f907584f06
Revises: 20a3b07767f
Create Date: 2014-08-14 22:24:25.254000

"""

# revision identifiers, used by Alembic.
revision = '37f907584f06'
down_revision = '20a3b07767f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
