"""empty message

Revision ID: 4c16f83552e5
Revises: None
Create Date: 2014-08-05 22:57:32.363000

"""

# revision identifiers, used by Alembic.
revision = '4c16f83552e5'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
